const countryData = {'FO': {'name': 'Faroe Islands', 'location': 'Europe'},
'UM': {'name': 'United States Minor Outlying Islands',
 'location': 'North America'},
'US': {'name': 'United States', 'location': 'North America'},
'JP': {'name': 'Japan', 'location': 'Eastern Asia'},
'SC': {'name': 'Seychelles', 'location': 'Seven seas (open ocean)'},
'IN': {'name': 'India', 'location': 'Southern Asia'},
'FR': {'name': 'France', 'location': 'Western Europe'},
'FM': {'name': 'Federated States of Micronesia', 'location': 'Oceania'},
'CN': {'name': 'China', 'location': 'Eastern Asia'},
'PT': {'name': 'Portugal', 'location': 'Southern Europe'},
'SW': {'name': 'Serranilla Bank', 'location': 'North America'},
'SH': {'name': 'Scarborough Reef', 'location': 'Asia'},
'BR': {'name': 'Brazil', 'location': 'South America'},
'KI': {'name': 'Kiribati', 'location': 'Oceania'},
'PH': {'name': 'Philippines', 'location': 'Southeast Asia'},
'MX': {'name': 'Mexico', 'location': 'Central America'},
'ES': {'name': 'Spain', 'location': 'Southern Europe'},
'BU': {'name': 'Bajo Nuevo Bank (Petrel Is.)', 'location': 'North America'},
'MV': {'name': 'Maldives', 'location': 'Seven seas (open ocean)'},
'SP': {'name': 'Spratly Islands', 'location': 'Asia'},
'GB': {'name': 'United Kingdom', 'location': 'Northern Europe'},
'GR': {'name': 'Greece', 'location': 'Southern Europe'},
'AS': {'name': 'American Samoa', 'location': 'Oceania'},
'DK': {'name': 'Denmark', 'location': 'Northern Europe'},
'GL': {'name': 'Greenland', 'location': 'North America'},
'GU': {'name': 'Guam', 'location': 'Oceania'},
'MP': {'name': 'Northern Mariana Islands', 'location': 'Oceania'},
'PR': {'name': 'Puerto Rico', 'location': 'North America'},
'VI': {'name': 'United States Virgin Islands', 'location': 'North America'},
'CA': {'name': 'Canada', 'location': 'North America'},
'ST': {'name': 'Sao Tome and Principe', 'location': 'Africa'},
'CV': {'name': 'Cape Verde', 'location': 'Africa'},
'DM': {'name': 'Dominica', 'location': 'North America'},
'NL': {'name': 'Netherlands', 'location': 'Western Europe'},
'JM': {'name': 'Jamaica', 'location': 'North America'},
'WS': {'name': 'Samoa', 'location': 'Oceania'},
'OM': {'name': 'Oman', 'location': 'Western Asia'},
'VC': {'name': 'Saint Vincent and the Grenadines', 'location': 'North America'},
'TR': {'name': 'Turkey', 'location': 'Western Asia'},
'BD': {'name': 'Bangladesh', 'location': 'Southern Asia'},
'LC': {'name': 'Saint Lucia', 'location': 'North America'},
'NR': {'name': 'Nauru', 'location': 'Oceania'},
'NO': {'name': 'Norway', 'location': 'Northern Europe'},
'KN': {'name': 'Saint Kitts and Nevis', 'location': 'North America'},
'BH': {'name': 'Bahrain', 'location': 'Western Asia'},
'TO': {'name': 'Tonga', 'location': 'Oceania'},
'FI': {'name': 'Finland', 'location': 'Northern Europe'},
'ID': {'name': 'Indonesia', 'location': 'Southeast Asia'},
'MU': {'name': 'Mauritius', 'location': 'Seven seas (open ocean)'},
'SE': {'name': 'Sweden', 'location': 'Northern Europe'},
'TT': {'name': 'Trinidad and Tobago', 'location': 'North America'},
'MY': {'name': 'Malaysia', 'location': 'Southeast Asia'},
'PA': {'name': 'Panama', 'location': 'North America'},
'PW': {'name': 'Palau', 'location': 'Oceania'},
'TV': {'name': 'Tuvalu', 'location': 'Oceania'},
'MH': {'name': 'Marshall Islands', 'location': 'Oceania'},
'CL': {'name': 'Chile', 'location': 'South America'},
'TH': {'name': 'Thailand', 'location': 'Southeast Asia'},
'GD': {'name': 'Grenada', 'location': 'North America'},
'EE': {'name': 'Estonia', 'location': 'Eastern Europe'},
'AG': {'name': 'Antigua and Barbuda', 'location': 'North America'},
'TW': {'name': 'Taiwan', 'location': 'Asia'},
'BB': {'name': 'Barbados', 'location': 'North America'},
'IT': {'name': 'Italy', 'location': 'Southern Europe'},
'MT': {'name': 'Malta', 'location': 'Southern Europe'},
'VU': {'name': 'Vanuatu', 'location': 'Oceania'},
'SG': {'name': 'Singapore', 'location': 'Southeast Asia'},
'CY': {'name': 'Cyprus', 'location': 'Western Asia'},
'LK': {'name': 'Sri Lanka', 'location': 'Southern Asia'},
'KM': {'name': 'Comoros', 'location': 'Africa'},
'FJ': {'name': 'Fiji', 'location': 'Oceania'},
'RU': {'name': 'Russia', 'location': 'Eastern Europe'},
'VA': {'name': 'Vatican', 'location': 'Europe'},
'SM': {'name': 'San Marino', 'location': 'Europe'},
'KZ': {'name': 'Kazakhstan', 'location': 'Central Asia'},
'AZ': {'name': 'Azerbaijan', 'location': 'Western Asia'},
'TJ': {'name': 'Tajikistan', 'location': 'Central Asia'},
'LS': {'name': 'Lesotho', 'location': 'Africa'},
'UZ': {'name': 'Uzbekistan', 'location': 'Central Asia'},
'MA': {'name': 'Morocco', 'location': 'Northern Africa'},
'CO': {'name': 'Colombia', 'location': 'South America'},
'TL': {'name': 'East Timor', 'location': 'Asia'},
'TZ': {'name': 'Tanzania', 'location': 'Eastern Africa'},
'AR': {'name': 'Argentina', 'location': 'South America'},
'SA': {'name': 'Saudi Arabia', 'location': 'Western Asia'},
'PK': {'name': 'Pakistan', 'location': 'Southern Asia'},
'YE': {'name': 'Yemen', 'location': 'Western Asia'},
'AE': {'name': 'United Arab Emirates', 'location': 'Western Asia'},
'KE': {'name': 'Kenya', 'location': 'Eastern Africa'},
'PE': {'name': 'Peru', 'location': 'South America'},
'DO': {'name': 'Dominican Republic', 'location': 'Caribbean'},
'HT': {'name': 'Haiti', 'location': 'Caribbean'},
'PG': {'name': 'Papua New Guinea', 'location': 'Oceania'},
'AO': {'name': 'Angola', 'location': 'Central Africa'},
'KH': {'name': 'Cambodia', 'location': 'Southeast Asia'},
'VN': {'name': 'Vietnam', 'location': 'Southeast Asia'},
'MZ': {'name': 'Mozambique', 'location': 'Eastern Africa'},
'CR': {'name': 'Costa Rica', 'location': 'North America'},
'BJ': {'name': 'Benin', 'location': 'Western Africa'},
'NG': {'name': 'Nigeria', 'location': 'Western Africa'},
'IR': {'name': 'Iran', 'location': 'Southern Asia'},
'SV': {'name': 'El Salvador', 'location': 'North America'},
'SL': {'name': 'Sierra Leone', 'location': 'Africa'},
'GW': {'name': 'Guinea Bissau', 'location': 'Africa'},
'HR': {'name': 'Croatia', 'location': 'Central Europe'},
'BZ': {'name': 'Belize', 'location': 'Central America'},
'ZA': {'name': 'South Africa', 'location': 'Southern Africa'},
'CF': {'name': 'Central African Republic', 'location': 'Africa'},
'SD': {'name': 'Sudan', 'location': 'Northern Africa'},
'CD': {'name': 'Democratic Republic of the Congo', 'location': 'Central Africa'},
'KW': {'name': 'Kuwait', 'location': 'Western Asia'},
'DE': {'name': 'Germany', 'location': 'Western Europe'},
'BE': {'name': 'Belgium', 'location': 'Western Europe'},
'IE': {'name': 'Ireland', 'location': 'Northern Europe'},
'KP': {'name': 'North Korea', 'location': 'Eastern Asia'},
'KR': {'name': 'South Korea', 'location': 'Eastern Asia'},
'GY': {'name': 'Guyana', 'location': 'South America'},
'HN': {'name': 'Honduras', 'location': 'Central America'},
'MM': {'name': 'Myanmar', 'location': 'Southeast Asia'},
'GA': {'name': 'Gabon', 'location': 'Central Africa'},
'GQ': {'name': 'Equatorial Guinea', 'location': 'Central Africa'},
'NI': {'name': 'Nicaragua', 'location': 'Central America'},
'LV': {'name': 'Latvia', 'location': 'Eastern Europe'},
'UG': {'name': 'Uganda', 'location': 'Eastern Africa'},
'MW': {'name': 'Malawi', 'location': 'Eastern Africa'},
'AM': {'name': 'Armenia', 'location': 'Central Asia'},
'SX': {'name': 'Somaliland', 'location': 'Africa'},
'TM': {'name': 'Turkmenistan', 'location': 'Central Asia'},
'ZM': {'name': 'Zambia', 'location': 'Eastern Africa'},
'NC': {'name': 'Northern Cyprus', 'location': 'Asia'},
'MR': {'name': 'Mauritania', 'location': 'Africa'},
'DZ': {'name': 'Algeria', 'location': 'Northern Africa'},
'LT': {'name': 'Lithuania', 'location': 'Europe'},
'ET': {'name': 'Ethiopia', 'location': 'Eastern Africa'},
'ER': {'name': 'Eritrea', 'location': 'Africa'},
'GH': {'name': 'Ghana', 'location': 'Western Africa'},
'SI': {'name': 'Slovenia', 'location': 'Central Europe'},
'GT': {'name': 'Guatemala', 'location': 'Central America'},
'BA': {'name': 'Bosnia and Herzegovina', 'location': 'Europe'},
'JO': {'name': 'Jordan', 'location': 'Western Asia'},
'SY': {'name': 'Syria', 'location': 'Western Asia'},
'MC': {'name': 'Monaco', 'location': 'Europe'},
'AL': {'name': 'Albania', 'location': 'Southeastern Europe'},
'UY': {'name': 'Uruguay', 'location': 'South America'},
'MN': {'name': 'Mongolia', 'location': 'Eastern Asia'},
'RW': {'name': 'Rwanda', 'location': 'Eastern Africa'},
'SO': {'name': 'Somalia', 'location': 'Eastern Africa'},
'BO': {'name': 'Bolivia', 'location': 'South America'},
'CM': {'name': 'Cameroon', 'location': 'Central Africa'},
'CG': {'name': 'Republic of Congo', 'location': 'Africa'},
'EH': {'name': 'Western Sahara', 'location': 'Africa'},
'RS': {'name': 'Serbia', 'location': 'Southern Europe'},
'ME': {'name': 'Montenegro', 'location': 'Europe'},
'TG': {'name': 'Togo', 'location': 'Western Africa'},
'LA': {'name': 'Laos', 'location': 'Asia'},
'AF': {'name': 'Afghanistan', 'location': 'Southern Asia'},
'UA': {'name': 'Ukraine', 'location': 'Eastern Europe'},
'SK': {'name': 'Slovakia', 'location': 'Europe'},
'JK': {'name': 'Siachen Glacier', 'location': 'Asia'},
'BG': {'name': 'Bulgaria', 'location': 'Eastern Europe'},
'QA': {'name': 'Qatar', 'location': 'Western Asia'},
'LI': {'name': 'Liechtenstein', 'location': 'Europe'},
'AT': {'name': 'Austria', 'location': 'Western Europe'},
'SZ': {'name': 'Eswatini', 'location': 'Africa'},
'HU': {'name': 'Hungary', 'location': 'Eastern Europe'},
'RO': {'name': 'Romania', 'location': 'Eastern Europe'},
'NE': {'name': 'Niger', 'location': 'Western Africa'},
'LU': {'name': 'Luxembourg', 'location': 'Central Europe'},
'AD': {'name': 'Andorra', 'location': 'Western Europe'},
'CI': {'name': 'Ivory Coast', 'location': 'Western Africa'},
'LR': {'name': 'Liberia', 'location': 'Western Africa'},
'BN': {'name': 'Brunei', 'location': 'Asia'},
'IQ': {'name': 'Iraq', 'location': 'Western Asia'},
'GE': {'name': 'Georgia', 'location': 'Central Asia'},
'GM': {'name': 'Gambia', 'location': 'Western Africa'},
'CH': {'name': 'Switzerland', 'location': 'Western Europe'},
'TD': {'name': 'Chad', 'location': 'Central Africa'},
'KV': {'name': 'Kosovo', 'location': 'Europe'},
'LB': {'name': 'Lebanon', 'location': 'Western Asia'},
'DJ': {'name': 'Djibouti', 'location': 'Eastern Africa'},
'BI': {'name': 'Burundi', 'location': 'Eastern Africa'},
'SR': {'name': 'Suriname', 'location': 'South America'},
'IL': {'name': 'Israel', 'location': 'Western Asia'},
'ML': {'name': 'Mali', 'location': 'Western Africa'},
'SN': {'name': 'Senegal', 'location': 'Western Africa'},
'GN': {'name': 'Guinea', 'location': 'Western Africa'},
'ZW': {'name': 'Zimbabwe', 'location': 'Eastern Africa'},
'PL': {'name': 'Poland', 'location': 'Eastern Europe'},
'MK': {'name': 'North Macedonia', 'location': 'Southeastern Europe'},
'PY': {'name': 'Paraguay', 'location': 'South America'},
'BY': {'name': 'Belarus', 'location': 'Eastern Europe'},
'CZ': {'name': 'Czech Republic', 'location': 'Eastern Europe'},
'BF': {'name': 'Burkina Faso', 'location': 'Western Africa'},
'NA': {'name': 'Namibia', 'location': 'Southern Africa'},
'LY': {'name': 'Libya', 'location': 'Northern Africa'},
'TN': {'name': 'Tunisia', 'location': 'Northern Africa'},
'BT': {'name': 'Bhutan', 'location': 'Eastern Asia'},
'MD': {'name': 'Moldova', 'location': 'Eastern Europe'},
'SS': {'name': 'South Sudan', 'location': 'Eastern Africa'},
'BW': {'name': 'Botswana', 'location': 'Africa'},
'BS': {'name': 'The Bahamas', 'location': 'North America'},
'NZ': {'name': 'New Zealand', 'location': 'Oceania'},
'CU': {'name': 'Cuba', 'location': 'Caribbean'},
'EC': {'name': 'Ecuador', 'location': 'South America'},
'AU': {'name': 'Australia', 'location': 'Oceania'},
'VE': {'name': 'Venezuela', 'location': 'South America'},
'SB': {'name': 'Solomon Islands', 'location': 'Oceania'},
'MG': {'name': 'Madagascar', 'location': 'Eastern Africa'},
'IS': {'name': 'Iceland', 'location': 'Northern Atlantic Ocean'},
'EG': {'name': 'Egypt', 'location': 'Northern Africa'},
'KG': {'name': 'Kyrgyzstan', 'location': 'Central Asia'},
'NP': {'name': 'Nepal', 'location': 'Southern Asia'}
};
  

const topCountries = [
    "CN",
    "KG",
    "IN",
    "US",
    "ID",
    "PK",
    "NA",
    "GM",
    "AL",
    "GE",
    "BT",
    "MN",
    "AM",
    "IS",
    "MK",
    "LB",
    "LY",
    "MT",
    "EE",
    "GA",
    "GQ",
    "NI",
    "AL",
    "LV",
    "DJ",
    "BR",
    "NG",
    "BD",
    "HR",
    "BZ",
    "RU",
    "MX",
    "JP",
    "ET",
    "PH",
    "EG",
    "VN",
    "CD",
    "SI",
    "TR",
    "IR",
    "DE",
    "TH",
    "GB",
    "FR",
    "IT",
    "TZ",
    "ZA",
    "MM",
    "KE",
    "KR",
    "CO",
    "ES",
    "UG",
    "AR",
    "DZ",
    "SD",
    "UA",
    "IQ",
    "AF",
    "PL",
    "CA",
    "MA",
    "SA",
    "UZ",
    "PE",
    "AO",
    "MY",
    "MZ",
    "GH",
    "YE",
    "NP",
    "VE",
    "MG",
    "CM",
    "CI",
    "KP",
    "AU",
    "NE",
    "LK",
    "BF",
    "ML",
    "RO",
    "MW",
    "CL",
    "KZ",
    "ZM",
    "GT",
    "EC",
    "SY",
    "NL",
    "SN",
    "KH",
    "TD",
    "SO",
    "ZW",
    "GN",
    "RW",
    "BJ",
    "BI",
    "TN",
    "BO",
    "BE",
    "HT",
    "CU",
    "SS",
    "DO",
    "CZ",
    "GR",
    "JO",
    "PT",
    "AZ",
    "SE",
    "HN",
    "AE",
    "HU",
    "TJ",
    "BY",
    "AT",
    "PG",
    "RS",
    "CH",
    "IL",
    "TG"
];

export { countryData, topCountries };
